In [6]:
import torch
import pendulum
import numpy

In [25]:
# https://www.learnpytorch.io/00_pytorch_fundamentals/

In [7]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [11]:
# Back to a Python integer
scalar.item()

7

In [15]:
scalar.shape

torch.Size([])

In [12]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [18]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
TENSOR.ndim

3

In [24]:
# Dimensions go outer to inner
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
torch.cuda.is_available()

False